### ISSUE TITLE
Build Failed: You have not accepted the license agreements of the following SDK components

### ISSUE THREAD

**Issue by Tazer** [bitrise-io/steps-gradle-runner#18]
Hello,

I'm getting the following error when trying to build my app with bitrise.io

You have not accepted the license agreements of the following SDK components:
  **[com.android.support.constraint:constraint-layout:1.0.0-alpha4, com.android.support.constraint:constraint-layout-solver:1.0.0-alpha4]**.
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

```
 Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: You have not accepted the license agreements of the following SDK components:
[com.android.support.constraint:constraint-layout:1.0.0-alpha4, com.android.support.constraint:constraint-layout-solver:1.0.0-alpha4].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
	at com.android.builder.sdk.DefaultSdkLoader.checkResults(DefaultSdkLoader.java:516)
	at com.android.builder.sdk.DefaultSdkLoader.updateRepositories(DefaultSdkLoader.java:419)
	at com.android.build.gradle.internal.DependencyManager.collectArtifacts(DependencyManager.java:550)
	at com.android.build.gradle.internal.DependencyManager.gatherDependencies(DependencyManager.java:385)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:288)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:159)
	at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.java:364)
	at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:636)
	at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:633)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
	at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:629)
	at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:823)
	at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:494)
	at com.android.build.gradle.internal.VariantManager$1.call(VariantManager.java:269)
	at com.android.build.gradle.internal.VariantManager$1.call(VariantManager.java:266)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:265)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 44 more


BUILD FAILED
```

**Comment by viktorbenei** [comment]
Can you please try this: http://blog.bitrise.io/2016/08/19/android-could-not-find-appcompat-v7-how-to-update-preinstalled-packages.html

**Comment by gauravniv** [comment]
@viktorbenei that is not working, I am facing the same issue

**Comment by viktorbenei** [comment]
Please follow our new, up to date guide: https://bitrise-io.github.io/devcenter/android/frequent-android-issues/#alternative-solution-for-the-license-error

Let us know if that wouldn't work/help!

**Comment by gauravniv** [comment]
Hey @viktorbenei that worked ! Thanks!

**Comment by siddharthnaik7** [comment]
@gauravniv how did you implement: https://bitrise-io.github.io/devcenter/android/frequent-android-issues/#alternative-solution-for-the-license-error

**Comment by viktorbenei** [comment]
@siddharthnaik7 just follow the steps here http://devcenter.bitrise.io/android/frequent-android-issues/#alternative-solution-for-the-license-error

If you have any questions, let us know! :)

**Comment by ShkurtiA** [comment]
Can someone please check this problem is still occurring for me with the new constraint layout:

```
File /root/.android/repositories.cfg could not be loaded.
Checking the license for package Solver for ConstraintLayout 1.0.1 in /opt/android-sdk-linux/licenses
Warning: License for package Solver for ConstraintLayout 1.0.1 not accepted.
Checking the license for package ConstraintLayout for Android 1.0.1 in /opt/android-sdk-linux/licenses
Warning: License for package ConstraintLayout for Android 1.0.1 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [ConstraintLayout for Android 1.0.1, Solver for ConstraintLayout 1.0.1].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --info or --debug option to get more log output.
```
```

Caused by: java.lang.RuntimeException: You have not accepted the license agreements of the following SDK components:
[ConstraintLayout for Android 1.0.1, Solver for ConstraintLayout 1.0.1].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```


I tried adding this:

```
script:
        title: Do anything with Script step
        inputs:
        - content: |-
            set -ex
            $GRADLEW_PATH dependencies || true
            echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
            echo y | android update sdk --no-ui --all --filter extra-google-m2repository | grep 'package installed'
            echo y | android update sdk --no-ui --all --filter extra-google-google_play_services | grep 'package installed'
    - git-clone: {}
```

 but didnt fix it, does anyone have any solution for this problem?
Thanks

**Comment by viktorbenei** [comment]
Please see https://discuss.bitrise.io/t/android-sdk-license-issue/97/2 and comment there or create a new ticket there if you have any questions / issues.

**Comment by ShkurtiA** [comment]
Thanks for your fast answer. I dont like that kind of solution, I was looking about changing only the script, but as I can see that is my last chance, there is no other way sadly.

**Comment by viktorbenei** [comment]
@ShkurtiA just shared a couple of alternative solutions here: https://discuss.bitrise.io/t/android-sdk-license-issue/97/3?u=viktorbenei

**Comment by ShkurtiA** [comment]
Thanks man, I already followed the first one, but its good to know that this also works for bitrise, because I have seen this as an answer for other CI but didnt think to try it on bitrise. Good job 👍

**Comment by viktorbenei** [comment]
No problem, just a note, the current ZIP downloader step has an issue on Linux, one of the `cp` flags used in the step doesn't work the same on Linux as on MacOS, so the example there won't work right now, but we'll fix this ASAP. That said I think using a ZIP is more trouble than it worth, as the extract depends on with which ZIP program you created the ZIP. Some do include the root dir ("licenses" in this case) in the ZIP (e.g. MacOS always includes a root directory in the ZIP), while others only include the files, so the extract path depends on the content/structure of the ZIP.

**Comment by gitGksgk** [comment]
I'm not sure if it'd been said, but looking for sdkmanager and type 
$ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" 
$ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
work for me

**Comment by viktorbenei** [comment]
Just a note: our current recommendation is to use the **Install missing Android tools** step, which should take care of these missing tools which require a license to be accepted: https://discuss.bitrise.io/t/android-automatic-dependency-installer-e-g-build-tools-step-install-missing-android-tools/316

**Comment by miankhalid** [comment]
_Incase the above solutions didn't work out for anyone in 2018_ 😉 

There's already a closed issue for this on Travis's Issue page and one of the mentioned solutions on it is definitely working currently.

Exact link to solution: https://github.com/travis-ci/travis-ci/issues/6617#issuecomment-369580270

**Comment by viktorbenei** [comment]
Thanks @miankhalid - but I'd still suggest you to rather use our **Install missing Android tools** step (if you're using bitrise). The step works reliably and we push step updates whenever something significant changes, which if you'd use a script instead you'd need to rewrite your script - with the step you just upgrade to the latest version ;)

**Comment by miankhalid** [comment]
@viktorbenei tbvh I've never used bitrise.io. I just stumbled upon this issue through google and while skimming over some of the issues that matched my search keywords found it.

So, trying to be a better citizen in the community is what drove me to share the solution that worked for me in hopes that it might save someone else's time ;)

**Comment by viktorbenei** [comment]
Sure, absolutely no problem @maciekjanusz ! ;) Quick note, Bitrise CLI is open source and can be used without bitrise.io (https://github.com/bitrise-io/bitrise) as well as this step and the Install Missing Android tools one (actually pretty much all steps, as all are open source, but there are service dependent ones like obviously the Deploy to Bitrise.io step requires bitrise.io :D )

**Comment by miankhalid** [comment]
Great! I might try it out in my free time .. thanks anyways 😸 

p.s. u tagged the wrong guy 😉

**Comment by viktorbenei** [comment]
Ouch, sorry maciekjanusz and thanks @miankhalid - feel free to [ping us](https://www.bitrise.io/contact) if you'd have any questions! ;)

**Comment by miankhalid** [comment]
Sure! Will do.

**Comment by s2zaman** [comment]
My `$ANDROID_HOME` was set to `sdk-root-directory/tools/bin`

I Updated the `$ANDROID_HOME` to its correct path `sdk-root-directory`
and added to PATH as `$ANDROID_HOME/tools/bin`
:)
