### ISSUE TITLE
Build Failed: Failed to install SDK components.

### ISSUE THREAD

**Issue by carlbenson** [bitrise-io/steps-gradle-runner#20]
This is actually an issue with the SDK tool from Google, which reports that installation of ConstraintLayout libraries fail although they are actually installed, but it fails the build as a result. Is there a work-around available?

```
    Caused by: java.lang.RuntimeException: Failed to install the following SDK components:
[Solver for ConstraintLayout 1.0.0-beta4, ConstraintLayout for Android 1.0.0-beta4]
Please install the missing components using the SDK manager in Android Studio.
	at com.android.builder.sdk.DefaultSdkLoader.checkResults(DefaultSdkLoader.java:542)
	at com.android.builder.sdk.DefaultSdkLoader.updateRepositories(DefaultSdkLoader.java:419)
	at com.android.build.gradle.internal.DependencyManager.collectArtifacts(DependencyManager.java:525)
	at com.android.build.gradle.internal.DependencyManager.gatherDependencies(DependencyManager.java:379)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:282)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:159)
	at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.java:364)
	at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:636)
	at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:633)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
	at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:629)
	at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:823)
	at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:494)
	at com.android.build.gradle.internal.VariantManager$1.call(VariantManager.
```

**Comment by viktorbenei** [comment]
Duplicate of https://github.com/bitrise-io/build.issues/issues/1
