### ISSUE TITLE
package.json (No such file or directory)

### ISSUE THREAD

**Issue by renatobenks** [bitrise-io/steps-gradle-runner#56]
Please, any idea is welcome, I'm getting this error to every builds and has been kinda impossible find out what's happening.

Maybe, could be related the VM that has been created by bitrise through of vagrant like described into logs, with all the source files copied, anyways, could be related too with the own graddle-runner.

bitrise.yml:

```yml
---
format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native
trigger_map:
- push_branch: master
  workflow: primary
- push_branch: production
  workflow: deploy
- workflow: primary
  pull_request_target_branch: master
workflows:
  deploy:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.9: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - npm@0.9.0:
        inputs:
        - command: install
    - install-missing-android-tools@2.1.1: {}
    - gradle-runner@1.8.3:
        inputs:
        - gradle_file: "$GRADLE_BUILD_FILE_PATH"
        - gradle_task: assembleRelease
        - gradlew_path: "$GRADLEW_PATH"
    - certificate-and-profile-installer@1.9.2: {}
    - xcode-archive@2.4.6:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - export_method: "$BITRISE_EXPORT_METHOD"
        - configuration: Release
    - cache-push@2.0.5:
        inputs:
        - compress_archive: 'true'
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.10:
        inputs:
        - branch_dest: master
        - branch: master
    - cache-pull@2.0.1:
        inputs:
        - is_debug_mode: 'true'
    - yarn@0.0.7:
        inputs:
        - command: install
    - script@1.1.5:
        inputs:
        - content: |
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            # write your script here
            export APP_PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
            export APP_PACKAGE_VERSION_CODE=$(cat package.json | grep versionCode | head -1 | awk -F: '{ print $2 }' | sed 's/[,]//g' | tr -d '[[:space:]]')
    - install-missing-android-tools@2.1.1: {}
    - gradle-runner@1.8.3:
        inputs:
        - gradle_task: assembleRelease
        - apk_file_include_filter: "*release*.apk"
    - cache-push@2.0.5:
        inputs:
        - compress_archive: 'true'
        - is_debug_mode: 'true'
    - hockeyapp-deploy-android@1.2.1:
        inputs:
        - api_token: HOCKEY_APP_TOKEN
        - app_id: HOCKEY_APP_ID
        - notes: |-
            # $BITRISE_APP_TITLE

            $BITRISE_GIT_MESSAGE

            Bitrise automatic deploy through HockeyApp Deploy Step.
        - notes_type: '1'
        - mapping_path: "$BITRISE_MAPPING_PATH"
app:
  envs:
  - opts:
      is_expand: false
    GRADLE_BUILD_FILE_PATH: android/build.gradle
  - opts:
      is_expand: false
    GRADLEW_PATH: android/gradlew
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: ios/LuvBook.xcodeproj
  - opts:
      is_expand: false
    BITRISE_SCHEME: LuvBook
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: development
```

Build logs
---

```
+------------------------------------------------------------------------------+

| (6) gradle-runner@1.8.3                                                      |
+------------------------------------------------------------------------------+
| id: gradle-runner                                                            |
| version: 1.8.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-04-28T22:32:46-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[22:32:46]  * [OK] Step dependency (go) installed, available. 
Configs:
- GradlewPath: android/gradlew
- GradleFile: android/build.gradle
- GradleTasks: assembleRelease
- GradleOptions: --stacktrace --no-daemon
- ApkFileIncludeFilter: *release*.apk
- ApkFileExcludeFilter: *unaligned.apk
*Test*.apk
- TestApkFileIncludeFilter: *Test*.apk
- TestApkFileExcludeFilter: 
- MappingFileIncludeFilter: */mapping.txt
- MappingFileExcludeFilter: 
- DeployDir: /Users/vagrant/deploy
- CacheLevel: only_deps
Running gradle task...
/Users/vagrant/git/android/gradlew "--build-file" "android/build.gradle" "assembleRelease" "--stacktrace" "--no-daemon"
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/vagrant/git/android/build.gradle' line: 54
* What went wrong:
A problem occurred evaluating root project 'LuvBook'.
> ../package.json (No such file or directory)
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'LuvBook'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.FileNotFoundException: ../package.json (No such file or directory)
	at build_cp5u57185wrunyb0c23n3lvat.getNpmVersion(/Users/vagrant/git/android/build.gradle:54)
	at build_cp5u57185wrunyb0c23n3lvat$getNpmVersion.callCurrent(Unknown Source)
	at build_cp5u57185wrunyb0c23n3lvat.getNpmVersionArray(/Users/vagrant/git/android/build.gradle:65)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:374)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject.invokeMethod(ExtensibleDynamicObject.java:245)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
	at build_cp5u57185wrunyb0c23n3lvat$_run_closure2$_closure7.doCall(/Users/vagrant/git/android/build.gradle:43)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
	at build_cp5u57185wrunyb0c23n3lvat$_run_closure2.doCall(/Users/vagrant/git/android/build.gradle:42)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:107)
	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:888)
	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:893)
	at org.gradle.api.internal.project.AbstractProject.subprojects(AbstractProject.java:876)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:374)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_cp5u57185wrunyb0c23n3lvat.run(/Users/vagrant/git/android/build.gradle:41)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 50 more
BUILD FAILED
Total time: 5.604 secs
Gradle task failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | gradle-runner@1.8.3 (exit code: 1)                            | 14 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-gradle-runner/issues      |
| Source: https://github.com/bitrise-io/steps-gradle-runner                    |
+---+---------------------------------------------------------------+----------+
```

**Comment by renatobenks** [comment]
closing this because I could caught that error based on another's issues, and fix it!

the following code was in my `build.gradle`:

```groovy
def getNpmVersion() {
    def inputFile = new File("../package.json")
    def packageJson = new JsonSlurper().parseText(inputFile.text)
    return packageJson["version"]
}

def getNpmVersionCode() {
    def inputFile = new File("../package.json")
    def packageJson = new JsonSlurper().parseText(inputFile.text)
    return packageJson["versionCode"]
}
```

Then, how it was displayed by error on the above logs, the `package.json` was not found because of the reference dispatched to run script, so, to solved that, I changed this lines to no more use a parcial path, for instead, use a full path provided by `projectDir` variable \o/

Bellow is the coded that fix it:

```groovy
def getNpmVersion() {
    def inputFile = new File(projectDir.getPath() + "/../package.json")
    def packageJson = new JsonSlurper().parseText(inputFile.text)
    return packageJson["version"]
}

def getNpmVersionCode() {
    def inputFile = new File(projectDir.getPath() + "/../package.json")
    def packageJson = new JsonSlurper().parseText(inputFile.text)
    return packageJson["versionCode"]
}
```

Anyways, thanks for community!

**Comment by viktorbenei** [comment]
Thanks @renatobenks for sharing the solution! I'm sure it'll help others in the future ;)
